name: vkio
description: VK API SDK is a Dart package allows you to access to all VK API methods such as Messages, Groups, Utils, etc.
version: 1.1.0
author: nitrojs <n1trojscoding@gmail.com>
homepage: https://github.com/nitreojs/dart-vkio
issue_tracker: https://github.com/nitreojs/dart-vkio/issues
dependencies:
  http: ^0.12.0+2
  html: ^0.14.0+2
environment:
  sdk: '>=2.2.2 <3.0.0'