name: vkio
description: VK API SDK is a Dart package allows you to access to all VK API methods such as Messages, Groups, Utils, etc.
version: 1.3.3
author: nitrojs <n1trojscoding@gmail.com>
homepage: https://github.com/nitreojs/dart-vkio
issue_tracker: https://github.com/nitreojs/dart-vkio/issues
dependencies:
  http: ^1.0.0
  html: ^0.15.0
  # dio: ^3.0.8
environment:
  sdk: '>=2.12.0 <3.0.0'